ft(roundTrip): Add round trip feature
andela/team-odd-bn-backend pull request #27
Opened 2019-11-18 20:20 UTC by ivymwende

#### What does this PR do?

Given that the requester is logged in, then the user should be able to enter where he is leaving from, where he is going to, date of travel, date of return, travel reasons, accommodation.

#### Description of Task to be completed?
[ ] Add return trip route
[ ] Add round trip data validations
[ ] Add round trip middlewares
[ ] Add round trip controllers

#### How should this be manually tested?
- Clone this repository using the command: `git clone https://github.com/andela/team-odd-bn-backend.git`
- Checkout to this branch using the command: `git checkout ft-return-trip-endpoint-169258637`
Run the application using the command: `npm run dev`
Run the tests using the command: `npm test`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#169258637](https://www.pivotaltracker.com/story/show/169258637)

#### Screenshots (if appropriate)

2019-11-21 05:30 UTC, NiyoEric commented on package.json
> +    "create-db-triprequestcities": "npx sequelize-cli model:generate --name triprequestcities --attributes tripRequestId:integer cityId:integer",
To avoid `package.json` to be complex, I recommend hiding all database scripts  in `.env` and use it when you want it.

2019-11-21 05:35 UTC, NiyoEric commented on src/database/migrations/20191118163016-create-users.js
> +      },
I have named it to `roleId`  and assign default value to be 3.
the column structure 
``` js
roleId : {
        type: Sequelize.INTEGER,
        defaultValue: 3,
        references: {  
          model: 'roles',
          key: 'id'
        }
      },
```

2019-11-21 05:37 UTC, NiyoEric commented on src/database/models/city.js
> +      // });
Remove the comment.

2019-11-21 05:39 UTC, NiyoEric commented on src/database/models/tripRequest.js
> +    })
Remember to add in all migrations and models association `ON CASCADE DELETE`. if a row of the referenced table is deleted, then all matching rows in the referencing table are deleted.

2019-11-21 05:39 UTC, NiyoEric commented on src/database/models/user.js
> +    users.hasMany(models.tripRequest, {
Add on `ON DELETE CASCADE`

2019-11-21 05:45 UTC, NiyoEric commented on src/helpers/AuthenticateToken.js
> +    const token = jwt.sign(newData, process.env.JWT_KEY, { expiresIn: 60 * 60 * 24 * 7 });
It is good to generate a token that expires after a short period, for instance `1W, 1D, 1M`

2019-11-21 05:46 UTC, NiyoEric commented on src/middlewares/TripMiddlewares.js
> + * @class Middlewares
it should be `@class TripMiddleware`.

2019-11-21 05:48 UTC, NiyoEric commented on src/middlewares/Validate.js
> + * @class ValidateUser
it should be `@class Validate`

2019-11-21 06:14 UTC, NiyoEric requested changes
Your work is good @ivymwende. please remember to apply the changes I requested and correct the bug found on `returnDate`.

2019-11-21 08:53 UTC, victkarangwa reviewed
Good work @ivymwende
Review some somments I left.

2019-11-21 08:53 UTC, victorkarangwa4 commented on src/database/models/tripRequest.js
> +    returnDate: DataTypes.STRING
I think you should have used  date datatype instead

2019-11-21 08:53 UTC, victorkarangwa4 commented on src/database/seeders/20191114145912-users.js
> +        signupType:'default',
I'm afraid that you used wrong value for isVerified. I think it should be true/false

2019-11-21 20:12 UTC, hezronkimutai reviewed
Nice work @ivymwende  just check on some few feedbacks I left.

2019-11-21 20:12 UTC, hezronkimutai commented on .eslintignore
> +tests/
Why are you ignoring the tests folder?

2019-11-21 20:12 UTC, hezronkimutai commented on .gitignore
>  # Dependency directories
Consider deleting and addind .DS_Store in the .gitignore

2019-11-21 20:12 UTC, hezronkimutai commented on src/controllers/TripController.js
> +   * User can be able to request one-way trip
Edit this comment. to return trip

2019-11-21 20:12 UTC, hezronkimutai commented on src/controllers/TripController.js
> +    )).catch(error => Customize.errorMessage(req, res, error.message, 404));
Change the status code of the catch block to be 500

2019-11-21 20:12 UTC, hezronkimutai commented on src/database/config/config.js
> +    "logging": false,
Nice initiative

2019-11-21 20:12 UTC, hezronkimutai commented on src/helpers/AuthenticateToken.js
> +/* eslint-disable require-jsdoc */
Remove this JSdoc comment and resolve the error

2019-11-21 20:12 UTC, hezronkimutai commented on src/middlewares/TripMiddlewares.js
> +      return Customize.errorMessage(req, res, 'Destination Id cannot be found!', 400);
Use status code 404 for not found

2019-11-21 20:12 UTC, hezronkimutai commented on src/middlewares/TripMiddlewares.js
> +      return Customize.errorMessage(req, res, 'Oops! originId doesn\'t exist!', 400);
use 404 for not found

2019-11-21 20:12 UTC, hezronkimutai commented on src/middlewares/TripMiddlewares.js
> +      return Customize.errorMessage(req, res, 'Oops!! You already have a scheduled trip during this duration', 400);
use 409 for conflict

2019-11-21 23:31 UTC, ivymwende commented on .eslintignore
> +tests/
Sorry removed it

2019-11-21 23:54 UTC, hezronkimutai approved these changes

2019-11-22 05:02 UTC, victkarangwa approved these changes
Good job @ivymwende 
I think you are now good to go since you've implemented the feedback.

2019-11-22 07:38 UTC, NiyoEric approved these changes

2019-11-22 09:47 UTC, merged

2019-11-22 09:47 UTC, julietezekwe reviewed
Looks good, great job