chore(readme): Update README file
andela/team-odd-bn-backend pull request #28
Opened 2019-11-19 15:58 UTC by victorkarangwa4

### What does this PR do?
Update README file 
#### Description of Task to be completed?
This PR update README file with guidance for running and testing the application
#### How should this be manually tested?
- Go to `ch-update-readme-file-169842519` branch
- Scroll down to the README file
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#169842519](https://www.pivotaltracker.com/story/show/169842519)
#### Screenshots
N/A
#### Questions:
N/A

2019-11-19 16:53 UTC, william000000 approved these changes

2019-11-19 16:53 UTC, william000000 reviewed
Good Job @victorkarangwa4

2019-11-19 18:28 UTC, ivymwende approved these changes
Great Job @victorkarangwa4 !

2019-11-20 05:15 UTC, NiyoEric approved these changes
You wrote a good readme @victorkarangwa4! we will update it as we along.

2019-11-20 09:32 UTC, hezronkimutai approved these changes

2019-11-20 10:07 UTC, ceelogre requested changes

2019-11-20 10:07 UTC, ceelogre commented on README.md
> +[Andela Kigali](https://www.andela.com) Team-odd
This link is irrelevant as it's for Andela global.

2019-11-20 10:07 UTC, ceelogre commented on README.md
> +| [/api/v1/auth/:id/resend-email](https://team-odd-bn-backend-staging.herokuapp.com/api/v1/auth/:id/resend-email) | GET |
This should be put in Documentation not here. Think about it,  as you progress you'll create new endpoints, will you keep adding them here?

2019-11-20 10:07 UTC, ceelogre commented on README.md
> +1. **Create** a `.env` file to put in all environmental variables
The project already has `.env.example` so as part of this pull request, you're supposed to rename it to `.env` then all users have to do is add the variables, not create new files.

2019-11-22 09:53 UTC, julietezekwe approved these changes

2019-11-22 10:42 UTC, merged