ft(get user requests): create a route for getting user requests
andela/team-odd-bn-backend pull request #29
Opened 2019-11-25 19:57 UTC by hezronkimutai

### What does this PR do?
- This PR gets all the users trip requests.
#### Description of Task to be completed?
- Create a route for getting all the requests of the user by id
#### How should this be manually tested?
`git clone https://github.com/andela/team-odd-bn-backend`
`git checkout ft-get-requests-169258640`
Open postman and test the `\trips` endpoint
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-11-26 12:47 UTC, hezronkimutai commented on src/middlewares/Exists.js
> +    return Customize.errorMessage(req, res, 'No request availlable', 404);
Change this status code.

2019-11-26 12:47 UTC, hezronkimutai commented on src/middlewares/isUserVerified.js
> +  const { email } = req.user || req.body;
Remove req.body

2019-11-27 15:31 UTC, NiyoEric approved these changes
You have done a good job @hezronkimutai.

2019-11-27 15:34 UTC, NiyoEric commented
Update your README @hezronkimutai

2019-11-27 16:07 UTC, ivymwende requested changes
Great job! @hezzie Great Job! I have however left a few comments.

2019-11-27 16:07 UTC, ivymwende commented on src/middlewares/Exists.js
> +  static async isUsersRequestExist(req, res, next) {
@hezronkimutai Please explain how this is different from the database query you made in your controller and it's importance?

2019-11-27 17:04 UTC, ivymwende reviewed
@hezronkimutai Great Job!! Please clarify on the comment i left

2019-11-28 05:54 UTC, hezronkimutai commented on src/middlewares/Exists.js
> +  static async isUsersRequestExist(req, res, next) {
This is a middleware meant to check if the user has any  requests,   the querry at the controller is a join of two tables. get all requests made by the user.

2019-11-28 06:36 UTC, ivymwende approved these changes

2019-11-28 06:36 UTC, ivymwende commented on src/tests/060-tripTest.js
> +        res.should.have.status(401);
@hezronkimutai Why us the status code 401 if the user is able to get his/her trip requests?

2019-11-28 09:02 UTC, victkarangwa reviewed
@hezronkimutai  Nice Job
Just have a look at a comment I've left

2019-11-28 09:02 UTC, victkarangwa commented on src/routes/api/tripRoute.js
> + */
Would do you mind adding a response for users without tokens?
like 
```
"401": 
description: No token provided
```

2019-11-29 09:43 UTC, victkarangwa approved these changes
@hezronkimutai Thanks for incorporating the feedback.
I think you are good to go!

2019-11-29 14:46 UTC, merged