Bg manager email 170258130
andela/team-odd-bn-backend pull request #55
Opened 2019-12-12 11:46 UTC by hezronkimutai

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2019-12-16 07:05 UTC, NiyoEric requested changes
Thanks for getting this done @hezronkimutai, @victorkarangwa4  and @william000000. I think we are good to go. I have left feedback I think it was forgotten.

2019-12-16 07:05 UTC, NiyoEric commented on src/controllers/AccommodationController.js
> +      console.log(err);
Remove console.

2019-12-16 07:05 UTC, NiyoEric commented on src/controllers/BookingController.js
> +      console.log(error);
Remove console.

2019-12-16 07:05 UTC, NiyoEric commented on src/helpers/EmailHelper.js
> +      console.log(err);
Remove consoles everywhere.

2019-12-16 07:05 UTC, NiyoEric commented on src/helpers/TripHelper.js
> +
Remove comment.

2019-12-16 07:05 UTC, NiyoEric commented on src/helpers/TripHelper.js
> +
Remove comment.

2019-12-16 07:05 UTC, NiyoEric commented on src/public/index.html
> +</html>
EOL

2019-12-16 07:05 UTC, NiyoEric commented on src/routes/api/accommodationRoute.js
> +    // isUserVerified,
I think this middleware is helpful. what do you think if it is added?

2019-12-16 07:05 UTC, NiyoEric commented on src/helpers/EmailHelper.js
> +      console.log(err);
Remove console.

2019-12-16 09:18 UTC, NiyoEric approved these changes

2019-12-16 09:27 UTC, victorkarangwa4 commented on src/controllers/AccommodationController.js
> +      return Response.successMessage(req, res, 'Accommodation/s successfully fetched', accommodations, 200);
I think if you want to specify accommodation/accommodations, simply write `accommodation(s)`

2019-12-16 09:55 UTC, ivymwende approved these changes
Looks good to me! Great work Hezron!

2019-12-16 10:04 UTC, victkarangwa approved these changes
Good job!

2019-12-16 11:15 UTC, william000000 commented on src/database/models/booking.js
>    }, {});
@hezronkimutai  Why have you removed `userId` in this table?

2019-12-16 11:15 UTC, william000000 commented on src/public/index.html
> +  const socket = io('https://team-odd-bn-backend-staging.herokuapp.com/');
Nice work @hezronkimutai

2019-12-16 11:15 UTC, william000000 commented on src/services/BookingService.js
> +    const result = await CommonQueries.findAll(booking, findOneBookingObj);
may I know your intention here?

2019-12-16 11:18 UTC, william000000 reviewed
You have made a good initiative @hezronkimutai, However, there are some changes you made that you may explain to me well.

2020-01-01 23:24 UTC, shemaeric approved these changes
LGTM

2020-01-01 23:24 UTC, merged