ch(booking): change user booking response
andela/team-odd-bn-backend pull request #72
Opened 2020-02-05 07:49 UTC by victorkarangwa4

#### What does this PR do?
This PR changes the user booking response
#### Description of Task to be completed?
- Include accommodation information
- Include room information
#### How should this be manually tested?

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#171098744](https://www.pivotaltracker.com/story/show/171098744)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

2020-02-06 21:38 UTC, william000000 approved these changes
Good Job @victorkarangwa4

2020-02-06 21:40 UTC, NiyongaboEric approved these changes
Good initiative @victorkarangwa4 !

2020-02-06 21:41 UTC, NiyoEric approved these changes
Awesome job!

2020-02-10 15:35 UTC, hezronkimutai approved these changes
Nice work @victorkarangwa4

2020-02-12 13:19 UTC, nziokaivy requested changes
Great work @victorkarangwa4! Just remove those console logs and you are good to go!

2020-02-12 13:19 UTC, nziokaivy commented on src/controllers/BookingController.js
> +      console.log(error);
Please remove this console log

2020-02-12 13:19 UTC, nziokaivy commented on src/helpers/UserHelper.js
> +      console.log('====>', k);
remove this console.log as well

2020-02-14 06:51 UTC, william000000 commented on src/helpers/UserHelper.js
> +
Remove this console

2020-02-20 10:30 UTC, merged