ch(likeAndDislike) Return fully info about who liked or disliked
andela/team-odd-bn-backend pull request #75
Opened 2020-02-10 15:34 UTC by william000000

#### What does this PR do?
#### Description of Task to be completed?
#### How should this be manually tested?
#### Any background context you want to provide?
#### What are the relevant pivotal tracker stories?
#### Screenshots (if appropriate)
#### Questions:

2020-02-13 13:51 UTC, hezronkimutai requested changes
Please fill in the PR description @william000000

2020-02-13 14:07 UTC, NiyoEric requested changes
I 've tested likes/dislikes functionality and it is working as expected. Please take look the feedback I left

2020-02-13 14:07 UTC, NiyoEric commented on src/controllers/BookingController.js
> +
Remove console.

2020-02-20 14:11 UTC, hezronkimutai approved these changes

2020-02-20 14:12 UTC, hezronkimutai reviewed
Fix the failling tests @william000000

2020-02-20 14:12 UTC, NiyoEric approved these changes

2020-02-20 14:15 UTC, hezronkimutai approved these changes

2020-02-20 14:18 UTC, victkarangwa approved these changes
I think you are good to go!

2020-02-20 14:50 UTC, merged